package:
  name: general_robotics_toolbox
  version: 0.7.1

source:
  git_url: https://github.com/rpiRobotics/rpi_general_robotics_toolbox_py.git
  git_rev: 0.7.1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
    - numpy
    - pyyaml
  run:
    - python
    - numpy
    - pyyaml

test:
  requires:
    - pytest
  source_files:
    - test/
  imports:
    - pytest
  commands:
    - pytest test/ --verbose --ignore test/test_urdf_loader.py

about:
  home: https://github.com/rpiRobotics/rpi_general_robotics_toolbox_py
  license: BSD
  summary: Python robotics toolbox

